channels:
  - conda-forge

dependencies:
  # Conda packages
  - ffmpeg=4.3.1
  - ffmpeg-python=0.2.0
  - pip

  # Pip packages
  - pip:
      # Core packages
      - aiohttp==3.10.5
      - attrs==24.2.0
      - blinker==1.8.2
      - cachetools==5.5.0
      - certifi==2024.8.30
      - charset-normalizer==3.3.2
      - click==8.1.7
      - colorama==0.4.6
      - distro==1.9.0
      - filelock==3.16.0
      - frozenlist==1.4.1
      - fsspec==2024.9.0
      - greenlet==3.1.0
      - h11==0.14.0
      - idna==3.8
      - Jinja2==3.1.4
      - jsonschema==4.23.0
      - markdown-it-py==3.0.0
      - MarkupSafe==2.1.5
      - more-itertools==10.5.0
      - mpmath==1.3.0
      - numpy==1.26.4
      - orjson==3.10.7
      - packaging==24.1
      - pandas==2.2.2
      - pillow==10.4.0
      - protobuf==5.28.0
      - pyarrow==17.0.0
      - pycparser==2.22
      - pydantic==2.9.1
      - pydantic_core==2.23.3
      - Pygments==2.18.0
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - PyYAML==6.0.2
      - regex==2024.7.24
      - requests==2.32.3
      - rich==13.8.1
      - six==1.16.0
      - sniffio==1.3.1
      - SpeechRecognition==3.10.4
      - SQLAlchemy==2.0.34
      - streamlit==1.38.0
      - streamlit-mic-recorder
      - sympy==1.13.2
      - tenacity==8.5.0
      - tiktoken==0.7.0
      - toml==0.10.2
      - torch==2.4.1
      - tornado==6.4.1
      - tqdm==4.66.5
      - typing_extensions==4.12.2
      - tzdata==2024.1
      - urllib3==2.2.2
      - watchdog==4.0.2
      - yarl==1.11.1
      # - whisper==1.1.10
      - openai-whisper @ git+https://github.com/openai/whisper.git@279133e3107392276dc509148da1f41bfb532c7e

      # Additional packages
      - aiohappyeyeballs==2.4.0
      - anyio==4.4.0
      - altair==5.4.1
      - annotated-types==0.7.0
      - gitdb==4.0.11
      - GitPython==3.1.43
      - groq==0.11.0
      - httpcore==1.0.5
      - httpx==0.27.2
      - langchain==0.2.16
      - langchain-core==0.2.39
      - langchain-groq==0.1.9
      - langchain-text-splitters==0.2.4
      - langgraph-checkpoint==1.0.9
      - langsmith==0.1.117
      - llvmlite==0.43.0
      - mdurl==0.1.2
      - narwhals==1.7.0
      - networkx==3.3